application: restle
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /api/.*
  script: api.py
- url: /hulk/image_upload
  script: hulk_image_shim.py

skip_files:
- ^local/.*
- ^tests/.*
- ^.hg/.*
