application: substrate-docs
version: 1
runtime: python
api_version: 1


handlers:
- url: /(.*\.(css|png|js|html))
  static_files: static/_build/html/\1
  upload: static/_build/html/(.*\.(css|png|js|html))

- url: /
  static_files: static/_build/html/index.html
  upload: static/_build/html/index.html

skip_files:
- ^local/.*
- ^tests/.*
- ^.hg/.*
- ^.idea/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
